import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ReportQuestionSlider from "../components/QuestionForm";

function Explain() {
  const { reportId } = useParams();
  const [detection, setDetection] = useState(null);
  const [explanation, setExplanation] = useState(null);
  const [showQuestions, setShowQuestions] = useState(false);

  useEffect(() => {
    fetch(`/api/detections/${reportId}`)
      .then(res => res.json())
      .then(j => {
        if (j.status === "success") {
          setDetection(j.detection);
          setExplanation(j.explanation);
        }
      });
  }, [reportId]);

  if (!detection) {
    return (
      <>
        <Navbar />
        <div className="min-h-screen flex items-center justify-center bg-[#070b1a] text-cyan-300">
          🔍 Initializing forensic analysis…
        </div>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Navbar />

      <div className="min-h-screen bg-[#070b1a] text-gray-200 px-6 py-24">
        <div className="max-w-5xl mx-auto">

          {/* 🧠 Header */}
          <div className="mb-10 text-center">
            <h1 className="text-3xl font-bold text-cyan-400 tracking-wide">
              🧠 AI Deepfake Detection Report
            </h1>
            <p className="text-gray-400 mt-2">
              Advanced forensic explanation generated by AI
            </p>
          </div>

          {/* 🔎 Result Card */}
          <div className="bg-white/5 border border-cyan-500/20 rounded-2xl p-6 shadow-lg shadow-cyan-500/10 mb-10">
            <div className="flex justify-between items-center">
              <h2 className="text-xl font-semibold">
                Result:{" "}
                <span className="text-red-400">
                  {detection.result_label}
                </span>
              </h2>
              <span className="px-4 py-1 rounded-full bg-purple-600/20 text-purple-300 animate-pulse">
                Confidence {(detection.confidence * 100).toFixed(2)}%
              </span>
            </div>
          </div>

          {/* 🧩 Explanation Grid */}
          <div className="grid md:grid-cols-3 gap-6">

            {/* 👁 Visual */}
            <div className="bg-white/5 border border-white/10 rounded-xl p-5 hover:border-cyan-400 transition">
              <h3 className="font-semibold text-cyan-300 mb-3">
                👁 Visual Indicators
              </h3>
              <ul className="list-disc list-inside text-sm space-y-1">
                {(explanation.visual_clues || []).length
                  ? explanation.visual_clues.map((v, i) => (
                      <li key={i}>{v}</li>
                    ))
                  : <li>No visual anomalies detected</li>}
              </ul>
            </div>

            {/* ⚙ Technical */}
            <div className="bg-white/5 border border-white/10 rounded-xl p-5 hover:border-purple-400 transition">
              <h3 className="font-semibold text-purple-300 mb-3">
                ⚙ Technical Analysis
              </h3>
              <ul className="list-disc list-inside text-sm space-y-1">
                {(explanation.technical_analysis || []).length
                  ? explanation.technical_analysis.map((v, i) => (
                      <li key={i}>{v}</li>
                    ))
                  : <li>No technical flags</li>}
              </ul>
            </div>

            {/* 📊 Confidence */}
            <div className="bg-white/5 border border-white/10 rounded-xl p-5 hover:border-green-400 transition">
              <h3 className="font-semibold text-green-300 mb-3">
                📊 AI Confidence Reasoning
              </h3>
              <p className="text-sm">
                {explanation.confidence_reasoning ||
                  explanation.summary ||
                  "AI confidence explanation unavailable."}
              </p>
            </div>
          </div>

          {/* 🚨 CTA */}
          <div className="mt-12 text-center">
            <button
              onClick={() => setShowQuestions(true)}
              className="px-8 py-3 rounded-xl bg-red-600 hover:bg-red-700 text-white text-lg shadow-lg shadow-red-500/30"
            >
              🚨 Report Suspicious Content
            </button>
          </div>

          {showQuestions && (
            <div className="mt-10">
              <ReportQuestionSlider
                detectionId={detection.id}
                onClose={() => setShowQuestions(false)}
              />
            </div>
          )}

        </div>
      </div>

      <Footer />
    </>
  );
}

export default Explain;
